spring:
  application:
    name: ecommerce
  r2dbc:
    url: r2dbc:h2:file://././data/ecomm?options=AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  flyway:
    url: jdbc:h2:file:./data/ecomm;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE
    shemas: ecomm
    user: sa
    password:
  h2:
    console.enabled: true
    console.settings.web-allow-others: false


modern:
  api:
    h2:
      console:
        port: 8081