spring:
  datasource:
    name: ecomm
    url: jdbc:h2:mem:ecomm;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate.default_schema: ecomm
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:h2:mem:ecomm
    shemas: ecomm
    user: sa
    password:


app.security.jwt.key-alias: jwt-sign-key
app.security.jwt.private-key-passphrase: password
app.security.jwt.keystore-location: jwt-keystore.jks
app.security.jwt.keystore-password: password